Empty defaults for person props
PostHog/posthog-plugin-geoip pull request #11
Opened 2021-09-21 16:44 UTC by yakkomajuri

## Changes

It makes sense to skip certain props altogether in the general event properties, but it gets problematic with person properties. If one value doesn't get set, you run into weird scenarios.

I saw a user for example that was somewhere in Russia that GeoIP couldn't find a city for. What happened is they had something like "New York, Russia"

## Checklist

-   [ ] Tests for new code

2021-09-22 09:12 UTC, Twixes requested changes
I'm not sure about this. Empty string doesn't sound like the right way of signaling that the property's right value isn't known. Null maybe?
I would also love to have a test to see the difference.

2021-09-22 12:08 UTC, yakkomajuri commented on index.ts
> +                    }
ah yup sorry

2021-09-22 12:48 UTC, yakkomajuri commented
ya got it

2021-11-18 17:24 UTC, Twixes approved these changes
Oops! Somehow this got buried 😅 LGTM

2021-11-18 17:41 UTC, merged