wip set cache
PostHog/posthog-plugin-geoip pull request #5
Opened 2021-06-10 16:32 UTC by yakkomajuri

## Changes

...

## Checklist

-   [ ] Tests for new code

2021-06-17 10:54 UTC, Twixes requested changes
Hm, I think something is amiss here. This would result in most events having no `$geoip_` props in `properties`. That's not desired, because it'd mess up analytics on events.
What's been discussed is skipping `$geoip_` props **in `$set` and `$set_once`** when we are sure that they've already been set recently with the same values.

2021-06-17 11:10 UTC, yakkomajuri commented
Right yeah, good point - this PR was an example I wrote up in 5 min. Also need to substitute the storage for cache.

2021-06-22 16:19 UTC, yakkomajuri commented
updated @Twixes

2021-07-08 13:25 UTC, yakkomajuri commented
Tested on playground, will merge

2021-07-08 13:25 UTC, merged

2021-07-08 13:30 UTC, Twixes commented
Ohh, sorry, didn't review this because apparently GitHub can only send reminders for up to 5 repos per day in #github-remindes, and apparently this repo hasn't been making it. Weird. So I didn't notice the review request. But code looks alright. 👍